### ISSUE TITLE
Autocompletion feature?

### ISSUE THREAD

**Issue by Neo42** [jacekm-git/Keepest-Android#11]
Would there be any options of autocompletion? Like you can input a word with some hints popping up. Like VSCode IntelleSence

**Comment by jacekm-git** [comment]
Hello,
thank you for your comment. I'm not convinced to your idea. There are hints displayed on android keyboard (at least gboard). 
![x](https://user-images.githubusercontent.com/3764340/42727933-c8046e32-879e-11e8-841b-6fd378935a88.jpg)
