### ISSUE TITLE
F-droid

### ISSUE THREAD

**Issue by guland2000** [jacekm-git/Keepest-Android#12]
Must be presented on [F-droid](https://f-droid.org/).

P.S.
Russian language is done.
Can we use other languages as [Toki Pona](https://en.wikipedia.org/wiki/Toki_Pona) etc?

**Comment by jacekm-git** [comment]
Unfortunately Keepest uses play services and will not be accepted by F-droid.

Thank you for translating the app to Russian language. I will include your work in the next release.

We can only use languages supported by Google Translate and Toki Pona is not one of them :/
