### ISSUE TITLE
Play Store Feature Graphic

### ISSUE THREAD

**Issue by mendezand** [jacekm-git/Keepest-Android#14]
Hello again.
As you requested by mail I have made this design for the application and be used in the Play Store. It contains the measures 1024x500px (if this is not correct please correct me).

I hope you like it. Do not doubt in telling me if you want some specific modification or a total modification.

![image](https://user-images.githubusercontent.com/38763253/43295389-947fad9c-9112-11e8-88d4-7f804e643a94.png)

Regards.

**Comment by jacekm-git** [comment]
Looks fantastic. My girlfriend approved, so I will accept it:)

**Comment by mendezand** [comment]
Great. I share the editable files [here](https://drive.google.com/open?id=13zTmdDI1CibY5WHPNsgNYkytEvv38EKn).

An honor to contribute to this application. :)
