### ISSUE TITLE
New Logo.

### ISSUE THREAD

**Issue by mendezand** [jacekm-git/Keepest-Android#8]
Hi.

I can create a new logo for your application. If you are interested contact me.
If you have some idea in mind you can share it with me and create a logo according to your application.

Greetings.

**Comment by jacekm-git** [comment]
Hi,
Yeah, sure. I'm interested. Unfortunately I'm not very artistic person,  so I don't have any particular idea about the logo. So it means you are not constrained by me. If your logo is decent, I will accept it. Thanks for your time.

**Comment by mendezand** [comment]
I will be working on it.

**Comment by mendezand** [comment]
Hello again.
Apologies for the delay, I've been a little busy.
I share my proposal:
![sin titulo-1](https://user-images.githubusercontent.com/38763253/42667180-ab8cf7de-8617-11e8-9481-b8d8411e13b3.png)
I created a dictionary and a polygon that together form the letter "K". I used the colors that appear in your application.
You can ask me for any modification or a total modification. I hope you like it.

Best regards.

**Comment by jacekm-git** [comment]
Thank you, it looks really good. I will update the app icon and promo graphics on the PlayStore. Could you send me separate files?

**Comment by mendezand** [comment]
Of course, I will be sending it to you.
I'm glad you liked it.

**Comment by mendezand** [comment]
Hi again, how are you?
I send you the editable files and the separate files, [click here](https://drive.google.com/drive/folders/1q8iAeWcK88Yhh39ECvfClCafIJNGVDsk?usp=sharing)

**Comment by jacekm-git** [comment]
Hi, I'm doing great. 
Thank you for the files. I'm gonna update app this weekend, and I'll add you in README.md as a contributor.
